name: platform_channel_events
description: A new Flutter application demonstrating how to stream data via platform event channels.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.1

flutter:
  uses-material-design: true
